version: '3'

services:
  clinica:
    build: clinica
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL : ${DB_URL}
      DB_NAME: ${DB_NAME}
      DB_USERNAME : ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET : ${JWT_SECRET}
    restart: always
    depends_on:
      clinica_db:
        condition: service_healthy
  clinica_db:
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: medpointclinic123
      MYSQL_PASSWORD: medpointclinic123
      MYSQL_DATABASE: clinica
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
