name: Deploy to Azure VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 1: Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker CLI
      uses: docker/setup-qemu-action@v2

    # Paso 2: Iniciar sesión en Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    # Paso 3: Verificar la estructura del repositorio
    - name: Check repository structure
      run: |
        ls -R

    # Paso 4: Construir la imagen Docker y etiquetarla
    - name: Build Docker image
      run: |
         docker build -t clinica-backend:latest -f ./clinica/Dockerfile ./clinica

    # Paso 5: Subir la imagen Docker a Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker tag clinica-backend:latest ${{ secrets.DOCKER_USERNAME }}/clinica-backend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/clinica-backend:latest

    # Paso 6: Conectar y desplegar en la máquina virtual de Azure
    - name: SSH to Azure VM and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          echo '${{ secrets.DOCKER_PASSWORD }}' | sudo docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
          
          # Detener el contenedor actual
          sudo docker-compose -f ClinicaApp/clinica-backend/docker-compose.yml down
          
          # Extraer la última imagen del contenedor
          sudo docker pull clinica-backend:latest
          
          # Subir y ejecutar el contenedor nuevo
          sudo docker-compose -f ClinicaApp/clinica-backend/docker-compose.yml up -d